/**********************************/
/* Table Name: 식단 카테고리 */
/**********************************/
DROP TABLE EATCATE;
DROP TABLE EATCATE CASCADE CONSTRAINTS;

DROP SEQUENCE EATCATE_SEQ;

CREATE SEQUENCE EATCATE_SEQ
    START WITH 1         -- 시작 번호
    INCREMENT BY 1       -- 증가값
    MAXVALUE 9999999999  -- 최대값: 9999999999 --> NUMBER(10) 대응
    CACHE 2              -- 2번은 메모리에서만 계산
    NOCYCLE;            

CREATE TABLE EATCATE(
		EATCATENO                         		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		ADMINNO                       		NUMBER(10)		 NOT NULL,
		IMAGE                         		VARCHAR2(10)		 NOT NULL,
		NAME                          		VARCHAR2(10)		 NOT NULL,
		NAMESUB                       		VARCHAR2(10)		 DEFAULT '-'		 NOT NULL,
		VISIBLE                       		CHAR(1)		 DEFAULT 'N'		 NOT NULL,
		EDATE                         		DATE		 NOT NULL
);

COMMENT ON TABLE EATCATE is '식단 카테고리';
COMMENT ON COLUMN EATCATE.EATCATENO is '식단 번호';
COMMENT ON COLUMN EATCATE.ADMINNO is '관리자 번호';
COMMENT ON COLUMN EATCATE.IMAGE is '식품 이미지';
COMMENT ON COLUMN EATCATE.NAME is '중분류';
COMMENT ON COLUMN EATCATE.NAMESUB is '소분류';
COMMENT ON COLUMN EATCATE.VISIBLE is '출력모드';
COMMENT ON COLUMN EATCATE.EDATE is '등록일';



-- CREATE
INSERT INTO EATCATE (EATCATENO, ADMINNO, IMAGE, NAME, NAMESUB, VISIBLE, EDATE)
VALUES (EATCATE_seq.nextval, 123456, 'image.jpg', 'Healthy', '-', 'N', TO_DATE('2024-05-13', 'YYYY-MM-DD'));


INSERT INTO EATCATE (EATCATENO, ADMINNO, IMAGE, NAME, NAMESUB, VISIBLE, EDATE)
VALUES (EATCATE_seq.nextval, 123456, 'image.jpg', 'Healthy', '-', 'N',sysdate);

INSERT INTO EATCATE (EATCATENO, ADMINNO, IMAGE, NAME, NAMESUB, VISIBLE, EDATE)
VALUES (EATCATE_seq.nextval, 1, 'image2.jpg', 'Healthy', '-', 'N',sysdate);


-- READ
SELECT EATCATENO, ADMINNO, IMAGE, NAME, NAMESUB, VISIBLE, EDATE 
FROM EATCATE;

SELECT EATCATENO, ADMINNO, IMAGE, NAME, NAMESUB, VISIBLE, EDATE 
FROM EATCATE
WHERE ADMINNO > 2;

-- UPDATE
UPDATE EATCATE
SET ADMINNO = 3
WHERE EATCATENO = 3;

UPDATE EATCATE
SET ADMINNO = 3
WHERE EATCATENO = 1;

DELETE FROM EATCATE
WHERE EATCATENO = 4;
