/**********************************/
/* Table Name: 리뷰 */
/**********************************/

DROP TABLE REIVIEW;
DROP TABLE REIVIEW CASCADE CONSTRAINTS;

DROP SEQUENCE REIVIEW_SEQ;

CREATE SEQUENCE REIVIEW_SEQ
    START WITH 1         -- 시작 번호
    INCREMENT BY 1       -- 증가값
    MAXVALUE 9999999999  -- 최대값: 9999999999 --> NUMBER(10) 대응
    CACHE 2              -- 2번은 메모리에서만 계산
    NOCYCLE;            

CREATE TABLE REIVIEW(
		REVIEWNO                      		NUMBER(10)		 NOT NULL		 PRIMARY KEY,
		STAR                          		NUMBER(10)		 DEFAULT 10		 NOT NULL,
		CONTENTS                      		VARCHAR2(10)		 NOT NULL,
		RDATE                         		DATE		 NOT NULL,
		CNT                           		NUMBER(10)		 DEFAULT 1		 NOT NULL,
		MEMBERNO                      		NUMBER(10)		 NOT NULL,
		EATNO                         		NUMBER(10)		 NOT NULL,
  FOREIGN KEY (MEMBERNO) REFERENCES MEMBER (MEMBERNO)
);

COMMENT ON TABLE REIVIEW is '리뷰';
COMMENT ON COLUMN REIVIEW.REVIEWNO is '리뷰번호';
COMMENT ON COLUMN REIVIEW.STAR is '별점';
COMMENT ON COLUMN REIVIEW.CONTENTS is '내용';
COMMENT ON COLUMN REIVIEW.RDATE is '등록일';
COMMENT ON COLUMN REIVIEW.CNT is '리뷰수';
COMMENT ON COLUMN REIVIEW.MEMBERNO is '회원 번호';
COMMENT ON COLUMN REIVIEW.EATNO is '식품 번호';

-- CREATE
INSERT INTO REIVIEW(REVIEWNO, STAR, CONTENTS, RDATE, CNT, MEMBERNO, EATNO)
VALUES (REIVIEW_seq.nextval, 9.0,'예시1',sysdate, 70, 1,1);

INSERT INTO REIVIEW(REVIEWNO, STAR, CONTENTS, RDATE, CNT, MEMBERNO, EATNO)
VALUES (REIVIEW_seq.nextval, 6.0,'예시2',sysdate, 7, 1,1);


INSERT INTO REIVIEW(REVIEWNO, STAR, CONTENTS, RDATE, CNT, MEMBERNO, EATNO)
VALUES (REIVIEW_seq.nextval, 7.0,'예시3',sysdate, 9, 1,1);

INSERT INTO REIVIEW(REVIEWNO, STAR, CONTENTS, RDATE, CNT, MEMBERNO, EATNO)
VALUES (REIVIEW_seq.nextval, 8.0,'예시4',sysdate, 10, 1,1);


-- READ
SELECT REVIEWNO, STAR, CONTENTS, RDATE, CNT, MEMBERNO, EATNO
FROM REIVIEW;

SELECT REVIEWNO, STAR, CONTENTS, RDATE, CNT, MEMBERNO, EATNO
FROM REIVIEW
WHERE STAR > 9.0;

-- UPDATE
UPDATE REIVIEW
SET STAR = 6.5
WHERE memberno = 1;

UPDATE REIVIEW
SET STAR = 7.0
WHERE memberno = 2;


-- DELETE
DELETE FROM REIVIEW
WHERE memberno = 4;

  
commit;
